version: 2
project_name: keysej

before:
  hooks:
    - go mod tidy

builds:
  - id: keysej
    main: ./main.go # adjust if your main package path is different
    binary: keysej
    env:
      - CGO_ENABLED=0
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]
    ldflags:
      - -s -w
      - -X main.version={{.Tag}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: archives
    name_template: "keysej_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - completions/* # if you generate static completions later

checksums:
  name_template: 'checksums.txt'

signs:
  - artifacts: checksum

changelog:
  use: github
  sort: asc

release:
  draft: false
  prerelease: false
