name: automerge-release-please
on:
  pull_request_target:
    types: [opened, reopened, labeled, synchronize, edited, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Debug PR labels
        run: echo '${{ toJSON(github.event.pull_request.labels) }}'

      - name: Gate on RP author + label
        if: >
          (
            github.event.pull_request.user.login == 'github-actions[bot]' ||
            github.event.pull_request.user.login == 'release-please[bot]'
          ) &&
          contains(toJSON(github.event.pull_request.labels.*.name), 'autorelease: pending') &&
          github.event.pull_request.base.ref == 'main'
        run: echo "Gate passed"

      - name: Wait for PR CI
        if: always() && steps.gate.outcome == 'success'
        uses: lewagon/wait-on-check-action@v1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: "ci / test"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - name: Merge (squash)
        if: always() && steps.gate.outcome == 'success'
        uses: peter-evans/merge-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request: ${{ github.event.pull_request.number }}
          merge-method: squash
