name: automerge-release-please
on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: >
      github.event.pull_request.base.ref == 'main' &&
      (
        github.event.pull_request.user.login == 'github-actions[bot]' ||
        github.event.pull_request.user.login == 'release-please[bot]'
      ) &&
      contains(
        join(fromJSON(toJSON(github.event.pull_request.labels)).*.name, ','),
        'autorelease: pending'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Wait for PR CI (unit tests)
        uses: lewagon/wait-on-check-action@v1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # MUST match the check name exactly as shown on the PR (e.g. "ci / test")
          check-name: "ci / test"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - name: Merge the PR (squash)
        uses: peter-evans/merge-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          pull-request: ${{ github.event.pull_request.number }}
