name: release-please
on:
  workflow_run:
    workflows: ["ci"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        id: rp
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable PR auto-merge (squash)
        if: ${{ steps.rp.outputs['pull-request-number'] }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr="${{ steps.rp.outputs['pull-request-number'] }}"
          echo "Enabling auto-merge for PR #$pr"
          gh pr merge --auto --squash "$pr"
