name: release-please
on:
  workflow_run:
    workflows: ["ci"]         # runs after your push CI
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        id: rp
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
