name: release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22'
      - run: go build -trimpath -ldflags "-s -w" -o keysej
      - uses: softprops/action-gh-release@v2
        with:
          files: keysej
