name: release
on:
  workflow_run:
    workflows: ["ci"]
    types: [completed]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-go@v5
        with: { go-version: '>=1.22' }

      - uses: actions/setup-node@v4
        with: { node-version: 22 }

      - name: Install semantic-release toolchain
        run: |
          npm i -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/github @semantic-release/exec

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
