name: release-please
on:
  push:
    branches: [ master ]
permissions:
  contents: write
  pull-requests: write
  id-token: write
concurrency:
  group: release-please
  cancel-in-progress: false
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}