name: release
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  release:
    needs: ci
    runs-on: ubuntu-latest
    concurrency:
      group: release-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx --yes -p semantic-release \
                  -p @semantic-release/commit-analyzer \
                  -p @semantic-release/release-notes-generator \
                  -p @semantic-release/changelog \
                  -p @semantic-release/git \
                  -p @semantic-release/github \
                  -p @semantic-release/exec \
            semantic-release